/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button } from 'react-native';
import Permissions from 'react-native-permissions';
import RNTwilioVoiceLibrary from 'react-native-twilio-voice-library';

/*
import { NativeModules } from 'react-native';
const { RNTwilioVoiceLibrary } = NativeModules; */

async function fetchAccessToken() {
  let response = await fetch(`<url_to_get_access_token>`);
  let data = await response.text()
  console.log('Access Token : ', data);
  return data;
}

async function initializeTwilioVoiceLibrary() {
  const accessToken = await fetchAccessToken();
  await RNTwilioVoiceLibrary.initWithAccessToken(accessToken);
  if (Platform.OS === 'ios') {
      RNTwilioVoiceLibrary.configureCallKit({
          appName: 'Twilio Example'
      });
  }
}

export default class App extends Component<{}> {

  async makeCall() {
    await initializeTwilioVoiceLibrary();
    Permissions.request('microphone').then(response => {
      if (response === 'authorized') {
        RNTwilioVoiceLibrary.connect({ To: '<phone_number>' });
      }
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆RNTwilioVoiceLibrary example☆</Text>
        <Button onPress={this.makeCall} title="Make Call"/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
